// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529225016_AddBaterija")]
    partial class AddBaterija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.EventPumpe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SesijaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SesijaId");

                    b.ToTable("event_pumpe", (string)null);
                });

            modelBuilder.Entity("api.Models.Mod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("mod", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "pull"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "push"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "timer"
                        });
                });

            modelBuilder.Entity("api.Models.Ocitavanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SesijaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Vlaga")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("SesijaId");

                    b.ToTable("ocitavanje", (string)null);
                });

            modelBuilder.Entity("api.Models.OcitavanjeBaterije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Postotak")
                        .HasColumnType("integer");

                    b.Property<int>("SesijaId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Vin")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("SesijaId");

                    b.ToTable("ocitavanje_baterije", (string)null);
                });

            modelBuilder.Entity("api.Models.Sesija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IntervalMinuta")
                        .HasColumnType("integer");

                    b.Property<int?>("IntervalPaljenja")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("Kraj")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModId")
                        .HasColumnType("integer");

                    b.Property<string>("Napomena")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Pocetak")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TrajanjePaljenja")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("sesija", (string)null);
                });

            modelBuilder.Entity("api.Models.EventPumpe", b =>
                {
                    b.HasOne("api.Models.Sesija", "Sesija")
                        .WithMany("EventiPumpe")
                        .HasForeignKey("SesijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesija");
                });

            modelBuilder.Entity("api.Models.Ocitavanje", b =>
                {
                    b.HasOne("api.Models.Sesija", "Sesija")
                        .WithMany("Ocitavanja")
                        .HasForeignKey("SesijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesija");
                });

            modelBuilder.Entity("api.Models.OcitavanjeBaterije", b =>
                {
                    b.HasOne("api.Models.Sesija", "Sesija")
                        .WithMany("OcitavanjaBaterije")
                        .HasForeignKey("SesijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesija");
                });

            modelBuilder.Entity("api.Models.Sesija", b =>
                {
                    b.HasOne("api.Models.Mod", "Mod")
                        .WithMany("Sesije")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("api.Models.Mod", b =>
                {
                    b.Navigation("Sesije");
                });

            modelBuilder.Entity("api.Models.Sesija", b =>
                {
                    b.Navigation("EventiPumpe");

                    b.Navigation("Ocitavanja");

                    b.Navigation("OcitavanjaBaterije");
                });
#pragma warning restore 612, 618
        }
    }
}
